name: typescript-action
description: Template of TypeScript Action

inputs:
  path:
    description: Path to the directory where the action is located
    required: true
    default: './'

runs:
  using: composite
  steps:
    - name: "Node"
      uses: actions/setup-node@v3
      with:
        node-version: 16
        main: 'dist/index.js'
        cache: yarn

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
          token: ${{ secrets.PAT }}
          commit-message: jerm
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: jermed
          delete-branch: true
          title: 'Create jerm request'
          body: |
            Create report
            - Created

            [1]: https://github.com/ST4RCHASER/monk-action
          labels: |
            report
            jerm
            monk
            automated pr
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
          base: ${{ github.head_ref }}

        

