name: typescript-action
description: Template of TypeScript Action

inputs:
  path:
    description: Path to the directory where the action is located
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - name: 'Prepare Node'
      uses: 'actions/setup-node@v3'
      with:
        node-version: 16
    - name: 'Start Modify...'
      run: node $GITHUB_ACTION_PATH/dist/index.js
    - name: 'Create Pull Reqests...'
      uses: peter-evans/create-pull-request@v4
