name: typescript-action
description: Template of TypeScript Action

inputs:
  path:
    description: Path to the directory where the action is located
    required: true
    default: './'

runs:
  using: 'node16'
  main: 'dist/index.js'
  
