name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn package
      - uses: int128/release-typescript-action@v1
        with:
          # TODO: change this on the stable release
          major-version: 0
    
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: jerm
          committer: Jerm Action <jerm@yue.sh>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: jermed
          delete-branch: true
          title: 'Create jerm request'
          body: |
            Create report
            - Created

            [1]: https://github.com/ST4RCHASER/monk-action
          labels: |
            report
            jerm
            monk
            automated pr
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
          base: ${{ github.head_ref }}